version: "3"
services:
  MockServer: 
    image: abdelrhmanhamdy/server
    ports:
      - "8282:8282"
  MysqlClient:
    env_file:
      - .Mysqlenv
    image: abdelrhmanhamdy/mysqlclient
    depends_on:
      - MockServer
    restart: on-failure:3
