    - name : Copy Docker Compose file
      copy: 
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yaml
    - name : Copy enviromentfile file
      copy: 
        src: .env
        dest: /home/ubuntu/.env
  
  
    - name: Log into DockerHub
      docker_login:
        username: "{{ dockeruser }}"
        password: "{{ dockerpass }}"
    
    - name: Run docker-compose File 
      command: docker-compose up -d --build
    
    - name: "Add docker-compose to run at startup "
      ansible.builtin.script: AddCronJob.sh
