    - name : Copy Docker Compose file
      copy: 
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yaml
    - name : Copy enviromentfile file
      copy: 
        src: .env
        dest: /home/ec2-user/.env
  
  
    - name: Log into DockerHub
      docker_login:
        username: "{{ dockeruser }}"
        password: "{{ dockerpass }}"
    
    - name: Run docker-compose File 
      command: docker-compose up -d 
    