---
- name : "configuration play"
  hosts: mockserver
  user: ubuntu
  become : true

  gather_facts: false
  vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "wait 200 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 200
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

  roles :
    - Disconnect_remove_MongoClient


