---
- name : "configuration play"
  hosts: mockserver
  user: ubuntu
  vars_files:
    - ./vars/dockerhub.yml

  become : true
  
  gather_facts: false
  vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes
    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes
    - name: "install Python and Docker for ansible"
      become: yes
      apt:
        name: ["python","pip"]
    - name: Install Docker python package for ansible
      ansible.builtin.pip:
        name: docker

  roles :
    #- install_docker
    - run_Server_client
