---
- name : "configuration play"
  hosts: mockserver
  user: ec2-user
  vars_files:
    - dockerhub.yml

  become : true
  
  gather_facts: false
  vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
    - name: Update yum cache
      ansible.builtin.yum:
        update_cache: true
        state : latest

  roles :
    - install_docker
    - install_docker_compose
    - run_Server_client
