---
- name : "Inastall and Configure Mongodb server"
  hosts: mongodb
  user: ec2-user
  become : true
  vars_files:
      - ./vars/MongoVars.yml
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python2
    - ansible_host_key_checking: false
 
  pre_tasks:

    - name: "wait 200 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 200
    - name: Update yum cache
      ansible.builtin.yum:
       update_cache: true
       state : latest

  roles :
    - install_configure_mongodb
