---
- name : "Inastall and Configure Mongodb server"
  hosts: all
  user: ec2-user
  vars_files:
    - MongoUsers.yml
  become : true
  
  gather_facts: false
 
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
    - name: Update yum cache
      ansible.builtin.yum:
       update_cache: true
       state : latest

  roles :
    - install_configure_mongodb
