---
  - name: Set Docker Repository
    become: true
    shell: |
        dpkg -s docker-ce
        if [ $? -nq 0 ]; then
        apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common lsb-release
        mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
        fi 
  - name : Install Docker
    become: true
    apt: 
      update_cache: yes
      name: ["docker-ce","docker-ce-cli","containerd.io","docker-buildx-plugin", "docker-compose-plugin"]
   
  - name : Add user to Docker group
    become: true  
    shell : |
       usermod -aG docker ubuntu 
  
  - name: Install Docker-Compose 
    become : true 
    shell: |
      curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
      chmod +x /usr/bin/docker-compose
     
  
      